server:
  port: 80

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: "${DATABASE_URL}"

  jpa:
    properties:
      physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServerDialect

resourcePath: "file:/images/"
