server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/album?serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

resourcePath: "file:///C:/images/"