spring:
  application:
    name: album_back
  output:
    ansi:
      enabled: always
  profiles:
    default: prod

jwt:
  access_token_expiration_time: 1800
  access_token_refresh_time: 86400000
  secret: ${JWT_SECRET}
