name: CI/CD

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Setting up JDK
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test
      - name: push into dockerhub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/album:1.0.0 .
          docker push ${{ secrets.DOCKER_USERNAME }}/album:1.0.0
      - name: into ssh
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop album
            sudo docker rm album
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker run --name album -d -p 80:80 -v /images:/images ${{ secrets.DOCKER_USERNAME }}/album:1.0.0 \
              -e DATABASE_URL=${{secrets.DATABASE_URL}} -e JWT_SECRET=${{secrets.JWT_SECRET}}