name: CI/CD

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Gradle Caching
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setting up JDK
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: push into dockerhub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build --build-arg DATABASE_URL="${{secrets.DATABASE_URL}}" --build-arg JWT_SECRET="${{secrets.JWT_SECRET}}" -t ${{ secrets.DOCKER_USERNAME }}/album .
          docker push ${{ secrets.DOCKER_USERNAME }}/album

      - name: into ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop album
            sudo docker rm album
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker run -e DATABASE_URL="${{secrets.DATABASE_URL}}" -dit -p 80:80 -v /images:/images --name album ${{ secrets.DOCKER_USERNAME }}/album